-- MySQL Script generated by MySQL Workbench
-- Fri May 31 17:34:29 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CMS
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CMS` ;

-- -----------------------------------------------------
-- Schema CMS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CMS` DEFAULT CHARACTER SET utf8 ;
USE `CMS` ;

-- -----------------------------------------------------
-- Table `CMS`.`generos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CMS`.`generos` ;

CREATE TABLE IF NOT EXISTS `CMS`.`generos` (
  `id_genero` INT NOT NULL AUTO_INCREMENT,
  `tipo_genero` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_genero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMS`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CMS`.`roles` ;

CREATE TABLE IF NOT EXISTS `CMS`.`roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre_rol` VARCHAR(50) NOT NULL,
  `estatus` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMS`.`nacionalidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CMS`.`nacionalidades` ;

CREATE TABLE IF NOT EXISTS `CMS`.`nacionalidades` (
  `id_nacionalidad` INT NOT NULL AUTO_INCREMENT,
  `nacionalidad` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_nacionalidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMS`.`paises`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CMS`.`paises` ;

CREATE TABLE IF NOT EXISTS `CMS`.`paises` (
  `id_pais` INT NOT NULL AUTO_INCREMENT,
  `nombre_pais` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMS`.`estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CMS`.`estados` ;

CREATE TABLE IF NOT EXISTS `CMS`.`estados` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `id_pais` INT NOT NULL,
  `nombre_estado` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_estado`),
  INDEX `fk_estados_paises1_idx` (`id_pais` ASC) ,
  CONSTRAINT `fk_estados_paises1`
    FOREIGN KEY (`id_pais`)
    REFERENCES `CMS`.`paises` (`id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMS`.`municipios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CMS`.`municipios` ;

CREATE TABLE IF NOT EXISTS `CMS`.`municipios` (
  `id_municipio` INT NOT NULL AUTO_INCREMENT,
  `id_estado` INT NOT NULL,
  `nombre_municipio` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_municipio`),
  INDEX `fk_municipios_estados1_idx` (`id_estado` ASC) ,
  CONSTRAINT `fk_municipios_estados1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `CMS`.`estados` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMS`.`parroquias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CMS`.`parroquias` ;

CREATE TABLE IF NOT EXISTS `CMS`.`parroquias` (
  `id_parroquia` INT NOT NULL AUTO_INCREMENT,
  `id_municipio` INT NOT NULL,
  `nombre_parroquia` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_parroquia`),
  INDEX `fk_parroquias_municipios1_idx` (`id_municipio` ASC) ,
  CONSTRAINT `fk_parroquias_municipios1`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `CMS`.`municipios` (`id_municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMS`.`codigos_postales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CMS`.`codigos_postales` ;

CREATE TABLE IF NOT EXISTS `CMS`.`codigos_postales` (
  `id_codigo_postal` INT NOT NULL AUTO_INCREMENT,
  `id_parroquia` INT NOT NULL,
  `numero_codigo_postal` INT NOT NULL,
  PRIMARY KEY (`id_codigo_postal`),
  INDEX `fk_codigos_postales_parroquias1_idx` (`id_parroquia` ASC) ,
  CONSTRAINT `fk_codigos_postales_parroquias1`
    FOREIGN KEY (`id_parroquia`)
    REFERENCES `CMS`.`parroquias` (`id_parroquia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMS`.`direcciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CMS`.`direcciones` ;

CREATE TABLE IF NOT EXISTS `CMS`.`direcciones` (
  `id_direccion` INT NOT NULL AUTO_INCREMENT,
  `id_codigo_postal` INT NOT NULL,
  `direccion_completa` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_direccion`),
  INDEX `fk_direcciones_codigos_postales1_idx` (`id_codigo_postal` ASC) ,
  CONSTRAINT `fk_direcciones_codigos_postales1`
    FOREIGN KEY (`id_codigo_postal`)
    REFERENCES `CMS`.`codigos_postales` (`id_codigo_postal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMS`.`personas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CMS`.`personas` ;

CREATE TABLE IF NOT EXISTS `CMS`.`personas` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `id_genero` INT NOT NULL,
  `id_rol` INT NOT NULL,
  `id_nacionalidad` INT NOT NULL,
  `id_direccion` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `cedula` INT NOT NULL,
  `correo_electronico` VARCHAR(50) NOT NULL,
  `clave` VARCHAR(50) NOT NULL,
  `facebook` VARCHAR(100) NOT NULL,
  `instagram` VARCHAR(100) NOT NULL,
  `x` VARCHAR(100) NOT NULL,
  `tiktok` VARCHAR(100) NOT NULL,
  `url_pagina` VARCHAR(45) NOT NULL,
  `img_pagina` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_persona`),
  INDEX `fk_personas_generos_idx` (`id_genero` ASC) ,
  INDEX `fk_personas_roles1_idx` (`id_rol` ASC) ,
  INDEX `fk_personas_nacionalidades1_idx` (`id_nacionalidad` ASC) ,
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC) ,
  INDEX `fk_personas_direcciones1_idx` (`id_direccion` ASC) ,
  CONSTRAINT `fk_personas_generos`
    FOREIGN KEY (`id_genero`)
    REFERENCES `CMS`.`generos` (`id_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personas_roles1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `CMS`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personas_nacionalidades1`
    FOREIGN KEY (`id_nacionalidad`)
    REFERENCES `CMS`.`nacionalidades` (`id_nacionalidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personas_direcciones1`
    FOREIGN KEY (`id_direccion`)
    REFERENCES `CMS`.`direcciones` (`id_direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMS`.`interfaces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CMS`.`interfaces` ;

CREATE TABLE IF NOT EXISTS `CMS`.`interfaces` (
  `id_interfaz` INT NOT NULL AUTO_INCREMENT,
  `nombre_interfaz` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_interfaz`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMS`.`options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CMS`.`options` ;

CREATE TABLE IF NOT EXISTS `CMS`.`options` (
  `id_obtions` INT NOT NULL AUTO_INCREMENT,
  `id_interfaz` INT NOT NULL,
  `id_persona` INT NOT NULL,
  `titulo` VARCHAR(20) NOT NULL,
  `contenido` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_obtions`),
  INDEX `fk_contenidos_interfaces1_idx` (`id_interfaz` ASC) ,
  INDEX `fk_options_personas1_idx` (`id_persona` ASC) ,
  CONSTRAINT `fk_contenidos_interfaces1`
    FOREIGN KEY (`id_interfaz`)
    REFERENCES `CMS`.`interfaces` (`id_interfaz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_options_personas1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `CMS`.`personas` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMS`.`permisos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CMS`.`permisos` ;

CREATE TABLE IF NOT EXISTS `CMS`.`permisos` (
  `id_permiso` INT NOT NULL AUTO_INCREMENT,
  `nombre_permiso` VARCHAR(50) NOT NULL,
  `descripcion_permiso` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_permiso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMS`.`asignaciones_roles_permisos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CMS`.`asignaciones_roles_permisos` ;

CREATE TABLE IF NOT EXISTS `CMS`.`asignaciones_roles_permisos` (
  `id_asignacion_rol_permiso` INT NOT NULL AUTO_INCREMENT,
  `id_rol` INT NOT NULL,
  `id_permiso` INT NOT NULL,
  PRIMARY KEY (`id_asignacion_rol_permiso`),
  INDEX `fk_asignaciones_roles_permisos_roles1_idx` (`id_rol` ASC) ,
  INDEX `fk_asignaciones_roles_permisos_permisos1_idx` (`id_permiso` ASC) ,
  CONSTRAINT `fk_asignaciones_roles_permisos_roles1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `CMS`.`roles` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asignaciones_roles_permisos_permisos1`
    FOREIGN KEY (`id_permiso`)
    REFERENCES `CMS`.`permisos` (`id_permiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CMS`.`publicaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CMS`.`publicaciones` ;

CREATE TABLE IF NOT EXISTS `CMS`.`publicaciones` (
  `id_publicacion` INT NOT NULL AUTO_INCREMENT,
  `id_persona` INT NOT NULL,
  `descripcion_publicacion` VARCHAR(200) NOT NULL,
  `fecha` DATE NOT NULL,
  `imagen` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_publicacion`),
  INDEX `fk_publicaciones_personas1_idx` (`id_persona` ASC) ,
  CONSTRAINT `fk_publicaciones_personas1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `CMS`.`personas` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
